### ISSUE TITLE
Flow vs Stream vs Enum

### ISSUE THREAD

**Issue by aoswalt** [nash-elixir/nash-elixir#5]
A tour of Flow compared to stream and enum

**Comment by andersonmcook** [comment]
We're going to download some novels in .txt and process a directory of them to find the most commonly occurring words.
I'll have some utility functions pre-defined and we'll write functions using Enum, Stream and Flow.

We'll also do a little benchmarking with Benchee to look at speed/memory usage.

I'll have the repo finished before the meetup: https://github.com/andersonmcook/flow_example
